#!/usr/bin/env bash

wget https://github.com/odin-lang/Odin/releases/download/dev-2025-09/odin-linux-amd64-dev-2025-09.zip
tar -xvzf odin-linux-amd64-dev-2025-09.zip
mv odin-linux-amd64-dev-2025-09 ~/.local/odin

